-- ***************************************************************************************************************************
-- *          CONSULTA DE TABLAS CATÁLOGO FEL-SV.                                                                            *
-- ***************************************************************************************************************************
SELECT C.* FROM CAT_000 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_001 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_002 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_003 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_004 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_005 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_006 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_007 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_008 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_009 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_010 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_011 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_012 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_013 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_014 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_015 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_016 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_017 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_018 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_019 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_020 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_021 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_022 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_023 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_024 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_025 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_026 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_027 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_028 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_029 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_030 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_031 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_032 C ORDER BY C.ID_CAT;
SELECT C.* FROM CAT_033 C ORDER BY C.ID_CAT;
-- ***************************************************************************************************************************
-- *          CONSULTA DE TABLAS EMISOR, SHAN, COMPAÑIA Y ESTABLECIMIENTO FEL-SV.                                            *
-- ***************************************************************************************************************************
SELECT F.* FROM EMISOR_V3 F;
SELECT F.* FROM EMISOR_KCOO_V3 F;
SELECT F.* FROM EMISOR_ESTABLECIMIENTO_V3 F;
SELECT F.* FROM NOTIFIACION_CORREO_V3 F;
SELECT F.* FROM IMPRESORAS F;
SELECT F.* FROM NOTIFICACIONES F;
-- ***************************************************************************************************************************
-- *          COMPROBANTE DE CRÉDITO FISCAL.                                                                                 *
-- ***************************************************************************************************************************
SELECT F.* FROM DTE_CCF_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM IDENTIFICACION_CCF_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM DOCU_RELA_CCF_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RECEPTOR_CCF_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM SHIPTO_CCF_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM OTROS_DOCU_CCF_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM VENTA_TERCERO_CCF_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM CUERPO_DOCU_CCF_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM CUERPO_TRIBUTO_CCF_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RESUMEN_CCF_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RESUMEN_TRIBUTO_CCF_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM EXTENSION_CCF_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM APENDICE_CCF_V3 F ORDER BY F.ID_DTE DESC;

SELECT F.* FROM DTE_CCF_V3 F WHERE F.ID_DTE IN (399);
SELECT F.* FROM IDENTIFICACION_CCF_V3 F WHERE F.ID_DTE IN (399);
SELECT F.* FROM DOCU_RELA_CCF_V3 F WHERE F.ID_DTE IN (399);
SELECT F.* FROM RECEPTOR_CCF_V3 F WHERE F.ID_DTE IN (399);
SELECT F.* FROM SHIPTO_CCF_V3 F WHERE F.ID_DTE IN (399);
SELECT F.* FROM OTROS_DOCU_CCF_V3 F WHERE F.ID_DTE IN (399);
SELECT F.* FROM VENTA_TERCERO_CCF_V3 F WHERE F.ID_DTE IN (399);
SELECT F.* FROM CUERPO_DOCU_CCF_V3 F WHERE F.ID_DTE IN (399);
SELECT F.* FROM CUERPO_TRIBUTO_CCF_V3 F WHERE F.ID_DTE IN (399);
SELECT F.* FROM RESUMEN_CCF_V3 F WHERE F.ID_DTE IN (399);
SELECT F.* FROM RESUMEN_TRIBUTO_CCF_V3 F WHERE F.ID_DTE IN (399);
SELECT F.* FROM EXTENSION_CCF_V3 F WHERE F.ID_DTE IN (399);
SELECT F.* FROM APENDICE_CCF_V3 F WHERE F.ID_DTE IN (399);
-- ***************************************************************************************************************************
-- *          NOTA DE CRÉDITO.                                                                                               *
-- ***************************************************************************************************************************
SELECT F.* FROM DTE_NC_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM IDENTIFICACION_NC_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM DOCU_RELA_NC_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RECEPTOR_NC_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM SHIPTO_NC_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM VENTA_TERCERO_NC_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM CUERPO_DOCU_NC_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM CUERPO_TRIBUTO_NC_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RESUMEN_NC_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RESUMEN_TRIBUTO_NC_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM EXTENSION_NC_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM APENDICE_NC_V3 F ORDER BY F.ID_DTE DESC;

SELECT F.* FROM DTE_NC_V3 F WHERE F.ID_DTE IN (25);
SELECT F.* FROM IDENTIFICACION_NC_V3 F WHERE F.ID_DTE IN (25);
SELECT F.* FROM DOCU_RELA_NC_V3 F WHERE F.ID_DTE IN (25);
SELECT F.* FROM RECEPTOR_NC_V3 F WHERE F.ID_DTE IN (25);
SELECT F.* FROM SHIPTO_NC_V3 F WHERE F.ID_DTE IN (25);
SELECT F.* FROM VENTA_TERCERO_NC_V3 F WHERE F.ID_DTE IN (25);
SELECT F.* FROM CUERPO_DOCU_NC_V3 F WHERE F.ID_DTE IN (25);
SELECT F.* FROM CUERPO_TRIBUTO_NC_V3 F WHERE F.ID_DTE IN (25);
SELECT F.* FROM RESUMEN_NC_V3 F WHERE F.ID_DTE IN (25);
SELECT F.* FROM RESUMEN_TRIBUTO_NC_V3 F WHERE F.ID_DTE IN (25);
SELECT F.* FROM EXTENSION_NC_V3 F WHERE F.ID_DTE IN (25);
SELECT F.* FROM APENDICE_NC_V3 F WHERE F.ID_DTE IN (25);
-- ***************************************************************************************************************************
-- *          NOTA DE DÉBITO.                                                                                                *
-- ***************************************************************************************************************************
SELECT F.* FROM DTE_ND_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM IDENTIFICACION_ND_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM DOCU_RELA_ND_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RECEPTOR_ND_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM SHIPTO_ND_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM VENTA_TERCERO_ND_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM CUERPO_DOCU_ND_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM CUERPO_TRIBUTO_ND_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RESUMEN_ND_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RESUMEN_TRIBUTO_ND_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM EXTENSION_ND_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM APENDICE_ND_V3 F ORDER BY F.ID_DTE DESC;

SELECT F.* FROM DTE_ND_V3 F WHERE F.ID_DTE IN (63);
SELECT F.* FROM IDENTIFICACION_ND_V3 F WHERE F.ID_DTE IN (1);
SELECT F.* FROM DOCU_RELA_ND_V3 F WHERE F.ID_DTE IN (1);
SELECT F.* FROM RECEPTOR_ND_V3 F WHERE F.ID_DTE IN (1);
SELECT F.* FROM SHIPTO_ND_V3 F WHERE F.ID_DTE IN (1);
SELECT F.* FROM VENTA_TERCERO_ND_V3 F WHERE F.ID_DTE IN (1);
SELECT F.* FROM CUERPO_DOCU_ND_V3 F WHERE F.ID_DTE IN (1);
SELECT F.* FROM CUERPO_TRIBUTO_ND_V3 F WHERE F.ID_DTE IN (1);
SELECT F.* FROM RESUMEN_ND_V3 F WHERE F.ID_DTE IN (1);
SELECT F.* FROM RESUMEN_TRIBUTO_ND_V3 F WHERE F.ID_DTE IN (1);
SELECT F.* FROM EXTENSION_ND_V3 F WHERE F.ID_DTE IN (1);
SELECT F.* FROM APENDICE_ND_V3 F WHERE F.ID_DTE IN (85);
-- ***************************************************************************************************************************
-- *          FACTURA ELECTRÓNICA.                                                                                           *
-- ***************************************************************************************************************************
SELECT F.* FROM DTE_F_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM IDENTIFICACION_F_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM DOCU_RELA_F_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RECEPTOR_F_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM SHIPTO_F_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM OTROS_DOCU_F_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM VENTA_TERCERO_F_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM CUERPO_DOCU_F_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM CUERPO_TRIBUTO_F_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RESUMEN_F_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RESUMEN_TRIBUTO_F_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM EXTENSION_F_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM APENDICE_F_V3 F ORDER BY F.ID_DTE DESC;

SELECT F.* FROM DTE_F_V3 F WHERE F.ID_DTE IN (177);
SELECT F.* FROM IDENTIFICACION_F_V3 F WHERE F.ID_DTE IN (177);
SELECT F.* FROM DOCU_RELA_F_V3 F WHERE F.ID_DTE IN (177);
SELECT F.* FROM RECEPTOR_F_V3 F WHERE F.ID_DTE IN (177);
SELECT F.* FROM SHIPTO_F_V3 F WHERE F.ID_DTE IN (177);
SELECT F.* FROM OTROS_DOCU_F_V3 F WHERE F.ID_DTE IN (177);
SELECT F.* FROM VENTA_TERCERO_F_V3 F WHERE F.ID_DTE IN (177);
SELECT F.* FROM CUERPO_DOCU_F_V3 F WHERE F.ID_DTE IN (177);
SELECT F.* FROM CUERPO_TRIBUTO_F_V3 F WHERE F.ID_DTE IN (177);
SELECT F.* FROM RESUMEN_F_V3 F WHERE F.ID_DTE IN (177);
SELECT F.* FROM RESUMEN_TRIBUTO_F_V3 F WHERE F.ID_DTE IN (177);
SELECT F.* FROM EXTENSION_F_V3 F WHERE F.ID_DTE IN (177);
SELECT F.* FROM APENDICE_F_V3 F WHERE F.ID_DTE IN (177);
-- ***************************************************************************************************************************
-- *          FACTURA DE EXPORTACIÓN.                                                                                        *
-- ***************************************************************************************************************************
SELECT F.* FROM DTE_FEX_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM IDENTIFICACION_FEX_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RECEPTOR_FEX_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM SHIPTO_FEX_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM OTROS_DOCU_FEX_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM VENTA_TERCERO_FEX_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM CUERPO_DOCU_FEX_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM CUERPO_TRIBUTO_FEX_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RESUMEN_FEX_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RESUMEN_TRIBUTO_FEX_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM EXTENSION_FEX_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM APENDICE_FEX_V3 F ORDER BY F.ID_DTE DESC;

SELECT F.* FROM DTE_FEX_V3 F WHERE F.ID_DTE IN (122);
SELECT F.* FROM IDENTIFICACION_FEX_V3 F WHERE F.ID_DTE IN (122);
SELECT F.* FROM RECEPTOR_FEX_V3 F WHERE F.ID_DTE IN (122);
SELECT F.* FROM SHIPTO_FEX_V3 F WHERE F.ID_DTE IN (122);
SELECT F.* FROM OTROS_DOCU_FEX_V3 F WHERE F.ID_DTE IN (122);
SELECT F.* FROM VENTA_TERCERO_FEX_V3 F WHERE F.ID_DTE IN (122);
SELECT F.* FROM CUERPO_DOCU_FEX_V3 F WHERE F.ID_DTE IN (122);
SELECT F.* FROM CUERPO_TRIBUTO_FEX_V3 F WHERE F.ID_DTE IN (122);
SELECT F.* FROM RESUMEN_FEX_V3 F WHERE F.ID_DTE IN (122);
SELECT F.* FROM RESUMEN_TRIBUTO_FEX_V3 F WHERE F.ID_DTE IN (122);
SELECT F.* FROM EXTENSION_FEX_V3 F WHERE F.ID_DTE IN (122);
SELECT F.* FROM APENDICE_FEX_V3 F WHERE F.ID_DTE IN (128);
-- ***************************************************************************************************************************
-- *          NOTA DE REMISION.                                                                                              *
-- ***************************************************************************************************************************
SELECT F.* FROM DTE_NR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM IDENTIFICACION_NR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM DOCU_RELA_NR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RECEPTOR_NR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM SHIPTO_NR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM OTROS_DOCU_NR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM VENTA_TERCERO_NR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM CUERPO_DOCU_NR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM CUERPO_TRIBUTO_NR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RESUMEN_NR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RESUMEN_TRIBUTO_NR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM EXTENSION_NR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM APENDICE_NR_V3 F ORDER BY F.ID_DTE DESC;

SELECT F.* FROM DTE_NR_V3 F WHERE F.ID_DTE IN (121);
SELECT F.* FROM IDENTIFICACION_NR_V3 F WHERE F.ID_DTE IN (121);
SELECT F.* FROM DOCU_RELA_NR_V3 F WHERE F.ID_DTE IN (121);
SELECT F.* FROM RECEPTOR_NR_V3 F WHERE F.ID_DTE IN (121);
SELECT F.* FROM SHIPTO_NR_V3 F WHERE F.ID_DTE IN (121);
SELECT F.* FROM OTROS_DOCU_NR_V3 F WHERE F.ID_DTE IN (121);
SELECT F.* FROM VENTA_TERCERO_NR_V3 F WHERE F.ID_DTE IN (121);
SELECT F.* FROM CUERPO_DOCU_NR_V3 F WHERE F.ID_DTE IN (121);
SELECT F.* FROM CUERPO_TRIBUTO_NR_V3 F WHERE F.ID_DTE IN (121);
SELECT F.* FROM RESUMEN_NR_V3 F WHERE F.ID_DTE IN (121);
SELECT F.* FROM RESUMEN_TRIBUTO_NR_V3 F WHERE F.ID_DTE IN (121);
SELECT F.* FROM EXTENSION_NR_V3 F WHERE F.ID_DTE IN (121);
SELECT F.* FROM APENDICE_NR_V3 F WHERE F.ID_DTE IN (121);
-- ***************************************************************************************************************************
-- *          COMPROBANTE DE RETENCIÓN.                                                                                      *
-- ***************************************************************************************************************************
SELECT F.* FROM DTE_CR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM IDENTIFICACION_CR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM DOCU_RELA_CR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RECEPTOR_CR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM SHIPTO_CR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM OTROS_DOCU_CR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM VENTA_TERCERO_CR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM CUERPO_DOCU_CR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM CUERPO_TRIBUTO_CR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RESUMEN_CR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM RESUMEN_TRIBUTO_CR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM EXTENSION_CR_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM APENDICE_CR_V3 F ORDER BY F.ID_DTE DESC;

SELECT F.* FROM DTE_CR_V3 F WHERE F.ID_DTE IN (71);
SELECT F.* FROM IDENTIFICACION_CR_V3 F WHERE F.ID_DTE IN (71);
SELECT F.* FROM DOCU_RELA_CR_V3 F WHERE F.ID_DTE IN (71);
SELECT F.* FROM RECEPTOR_CR_V3 F WHERE F.ID_DTE IN (71);
SELECT F.* FROM SHIPTO_CR_V3 F WHERE F.ID_DTE IN (71);
SELECT F.* FROM OTROS_DOCU_CR_V3 F WHERE F.ID_DTE IN (71);
SELECT F.* FROM VENTA_TERCERO_CR_V3 F WHERE F.ID_DTE IN (71);
SELECT F.* FROM CUERPO_DOCU_CR_V3 F WHERE F.ID_DTE IN (71);
SELECT F.* FROM CUERPO_TRIBUTO_CR_V3 F WHERE F.ID_DTE IN (71);
SELECT F.* FROM RESUMEN_CR_V3 F WHERE F.ID_DTE IN (71);
SELECT F.* FROM RESUMEN_TRIBUTO_CR_V3 F WHERE F.ID_DTE IN (71);
SELECT F.* FROM EXTENSION_CR_V3 F WHERE F.ID_DTE IN (71);
SELECT F.* FROM APENDICE_CR_V3 F WHERE F.ID_DTE IN (71);
-- ***************************************************************************************************************************
-- *          EVENTO DE INVALIDACIÓN.                                                                                        *
-- ***************************************************************************************************************************
SELECT F.* FROM DTE_INVALIDACION_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM IDENTIFICACION_INVALIDACION_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM DOCUMENTO_INVALIDACION_V3 F ORDER BY F.ID_DTE DESC;
SELECT F.* FROM MOTIVO_INVALIDACION_V3 F ORDER BY F.ID_DTE DESC;

SELECT F.* FROM DTE_INVALIDACION_V3 F WHERE F.ID_DTE IN (1);
SELECT F.* FROM IDENTIFICACION_INVALIDACION_V3 F WHERE F.ID_DTE IN (1);
SELECT F.* FROM DOCUMENTO_INVALIDACION_V3 F WHERE F.ID_DTE IN (1);
SELECT F.* FROM MOTIVO_INVALIDACION_V3 F WHERE F.ID_DTE IN (1);
-- ***************************************************************************************************************************
-- *          EVENTO DE CONTINGENCIA.                                                                                        *
-- ***************************************************************************************************************************
SELECT F.* FROM EVENTO_CONTINGENCIA_V3 F ORDER BY F.ID_CONTINGENCIA DESC;
SELECT F.* FROM IDENTIFICACION_CONTINGENCIA_V3 F ORDER BY F.ID_CONTINGENCIA DESC;
SELECT F.* FROM DETALLE_DTE_CONTINGENCIA_V3 F ORDER BY F.ID_CONTINGENCIA DESC;
SELECT F.* FROM MOTIVO_CONTINGENCIA_V3 F ORDER BY F.ID_CONTINGENCIA DESC;

SELECT F.* FROM EVENTO_CONTINGENCIA_V3 F WHERE F.ID_CONTINGENCIA IN (1);
SELECT F.* FROM IDENTIFICACION_CONTINGENCIA_V3 F WHERE F.ID_CONTINGENCIA IN (1);
SELECT F.* FROM DETALLE_DTE_CONTINGENCIA_V3 F WHERE F.ID_CONTINGENCIA IN (1);
SELECT F.* FROM MOTIVO_CONTINGENCIA_V3 F WHERE F.ID_CONTINGENCIA IN (1);
-- ***************************************************************************************************************************
-- *          CONSULTA JDE-FELSV.                                                                                            *
-- ***************************************************************************************************************************
SELECT F.* FROM PRODDTA.F5542FEL@JDEPD F;